Add manager profile editing functionality
Ashrockzzz2003/placement_tracker_server pull request #8
Opened 2024-12-31 20:02 UTC by Nandgopal-R

# Add API for Updating Manager Profile

### Description
This pull request adds an API endpoint `editManagerProfileById `  , which allows authorized user to update a manager's profile

### Features
- Added the editManagerProfileById  API endpoint
- Introduced a new  **POST**  route: `/manager/profile/edit`

This PR handles issue #4 

Please review @Ashrockzzz2003

2025-01-01 06:53 UTC, Ashrockzzz2003 requested changes
The goal is to update only the name. Please make changes accordingly. Only the manager themself will access this API. Therefore, userRole 0 is the only role authorised to use this route. Update logic to support that.

2025-01-01 06:53 UTC, Ashrockzzz2003 commented on controller/userWebController.js
> +            "managerPassword" : "<managerPassword>",
The `password` update will happen thru forget password and this. Insecure way! Also, email cannot be updated by the manager.

2025-01-01 06:53 UTC, Ashrockzzz2003 commented on controller/userWebController.js
> +            "accountStatus" : "<0/1/2>"
even this too. Only name can be edited.

2025-01-01 06:53 UTC, Ashrockzzz2003 commented on controller/userWebController.js
> +            if (req.body.userRole === null || req.body.userRole === undefined || req.body.userRole === "" || (req.body.userRole !== "1" && req.body.userRole !== "0" && req.body.userRole !== "2") ||
this is for the manager to update by themselves. hence userRole can only be `0`.

2025-01-01 07:13 UTC, Nandgopal-R commented
> The goal is to update only the name. Please make changes accordingly. Only the manager themself will access this API. Therefore, userRole 0 is the only role authorised to use this route. Update logic to support that.

Ohh ok, I'll change it

2025-01-01 16:28 UTC, Nandgopal-R commented
![Screenshot 2025-01-01 215423](https://github.com/user-attachments/assets/d460c8af-975f-4759-b2f9-c87bd0238cd9)

@Ashrockzzz2003, since only the name is being edited should I do all these checks or should I only validate the name of the manager and only pass the **name** of the manager in the **request body**?

2025-01-01 16:41 UTC, Ashrockzzz2003 commented
> ![Screenshot 2025-01-01 215423](https://private-user-images.githubusercontent.com/145009023/399575310-d460c8af-975f-4759-b2f9-c87bd0238cd9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU3NDk3NTQsIm5iZiI6MTczNTc0OTQ1NCwicGF0aCI6Ii8xNDUwMDkwMjMvMzk5NTc1MzEwLWQ0NjBjOGFmLTk3NWYtNDc1OS1iMmY5LWM4N2JkMDIzOGNkOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwMVQxNjM3MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDJmMmNhN2NlNmJiOGJmNWZlZDI1YmU2YTc0ZWYxNjMyOWJhNmMxYjJmMWJiZWZhMDJiMWEzYWQ4MTljMTY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rekXRfc1_jDdCm95Zzmp5fTgFmB0Ti8Qd0H70B2nRcs)
> 
> @Ashrockzzz2003, since only the name is being edited should I do all these checks or should I only validate the name of the manager and only pass the **name** of the manager in the **request body**?

The request body only will have the updated name.

1. The user role comes through the token validator. Validating if the userRole is that of manager is the first check.
2. With the `userEmail` field that's extracted from token, query the db to extract the managerId.
3. Validate the managerName now. Update it.

2025-01-01 16:59 UTC, Nandgopal-R commented
So a manager can only change his own name?

2025-01-01 17:18 UTC, Ashrockzzz2003 commented
> So a manager can only change his own name or they can change anyone's name?
> 
> If they are allowed to change anyone's name should'nt the id also be passed in the request body?

Yes
But this api is to edit only manager's name by themselves. Maybe we can extend it to allow admin to modify name. That case we'll need manager id. If you're planning to add that too, do it.

2025-01-01 17:31 UTC, Nandgopal-R commented
> > So a manager can only change his own name or they can change anyone's name?
> > If they are allowed to change anyone's name should'nt the id also be passed in the request body?
> 
> Yes But this api is to edit only manager's name by themselves. Maybe we can extend it to allow admin to modify name. That case we'll need manager id. If you're planning to add that too, do it.

I'll add it

2025-01-01 19:18 UTC, Nandgopal-R commented
@Ashrockzzz2003 I have made the changes

2025-05-01 06:57 UTC, Nandgopal-R commented
@Ashrockzzz2003 I have made the changes

2025-05-01 11:12 UTC, Ashrockzzz2003 commented
Why does it show up like a 1000 line change?

2025-05-02 14:17 UTC, Ashrockzzz2003 reviewed
LGTM

you missed a slash in route - added it.
id is now passed in token that automatically gets embedded to body on validation to use in APIs.
logic looks good
thanks for the contribution @Nandgopal-R 

unified formatting with prettier to avoid future PRs to have formatting as a change.

2025-05-02 14:18 UTC, Ashrockzzz2003 approved these changes

2025-05-02 14:19 UTC, merged